# Generated by Django 4.2.5 on 2025-05-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronef',
            name='immatriculation',
            field=models.CharField(default='XXXXX', max_length=6),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='indicatifRadio',
            field=models.CharField(default='F-JXXX', max_length=6),
        ),
    ]
