# Generated by Django 4.2.5 on 2025-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0002_aeronef_immatriculation_aeronef_indicatifradio'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronef',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='limiteAptitudeVol',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aeronef',
            name='limiteLSA',
            field=models.DateField(blank=True, null=True),
        ),
    ]
