# Generated by Django 4.2.5 on 2025-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0003_aeronef_date_aeronef_limiteaptitudevol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronef',
            name='limiteParachute',
            field=models.DateField(blank=True, null=True),
        ),
    ]
