# Generated by Django 4.2.5 on 2025-05-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0004_aeronef_limiteparachute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hInit', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('hEnd', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('textVol', models.CharField(blank=True, default='RAS', max_length=1000)),
                ('aeronef', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Intranet.aeronef')),
                ('bapteme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReservationBaptemeOuiNon', to='Intranet.ouinon')),
                ('instruction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReservationInstructionOuiNon', to='Intranet.ouinon')),
                ('location', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReservationLocationOuiNon', to='Intranet.ouinon')),
                ('maintenance', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ReservationMaintenanceOuiNon', to='Intranet.ouinon')),
                ('pilote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Intranet.member')),
            ],
        ),
    ]
