# Generated by Django 4.2.5 on 2025-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0006_reservation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='hEnd',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hInit',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
