# Generated by Django 4.2.5 on 2025-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0007_alter_reservation_hend_alter_reservation_hinit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date', 'hInit']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='bapteme',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='maintenance',
        ),
        migrations.AddField(
            model_name='reservation',
            name='typeVol',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
