# Generated by Django 4.2.5 on 2025-06-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0009_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='long',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
