# Generated by Django 5.1.5 on 2026-03-21 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0010_alter_city_options_city_lat_city_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetbudget',
            name='year',
            field=models.CharField(default=2026, max_length=4),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('fuselage', 'Fuselage'), ('aile_gauche', 'Aile gauche'), ('aile_droite', 'Aile droite'), ('moteur', 'Moteur'), ('helice', 'Hélice'), ('train', "Train d'atterrissage"), ('empennage', 'Empennage / Queue'), ('cockpit', 'Cockpit / Instruments'), ('parachute', 'Parachute'), ('electrique', 'Système électrique'), ('general', 'Général')], default='general', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField()),
                ('intervenant', models.CharField(max_length=200)),
                ('next_due', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('done', 'Terminé'), ('scheduled', 'Planifié'), ('issue', 'Anomalie détectée')], default='done', max_length=20)),
                ('aeronef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='Intranet.aeronef')),
                ('membre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Intranet.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('link', models.CharField(blank=True, default='', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notif_type', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('danger', 'Alerte')], default='info', max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Intranet.member')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='Intranet.member')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
